"""add idempotency key to jobs

Revision ID: 16a3ab210695
Revises: e780e18ef8b4
Create Date: 2026-03-12 22:03:33.700634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a3ab210695'
down_revision: Union[str, Sequence[str], None] = 'e780e18ef8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
