"""add dead letter fields to jobs

Revision ID: 4a8fc7fe6847
Revises: aae936cb27a1
Create Date: 2026-03-13 00:15:26.897204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8fc7fe6847'
down_revision: Union[str, Sequence[str], None] = 'aae936cb27a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "jobs",
        sa.Column(
            "is_dead_letter",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "dead_lettered_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.alter_column("jobs", "is_dead_letter", server_default=None)


def downgrade() -> None:
    op.drop_column("jobs", "dead_lettered_at")
    op.drop_column("jobs", "is_dead_letter")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dead_lettered_at')
    op.drop_column('jobs', 'is_dead_letter')
    # ### end Alembic commands ###
