"""add job event audit table

Revision ID: 89dba25a7b46
Revises: 079a4d12756d
Create Date: 2026-03-28 00:48:50.165290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dba25a7b46'
down_revision: Union[str, Sequence[str], None] = '079a4d12756d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_event_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_event_audit')
    # ### end Alembic commands ###
