"""add priority field to jobs

Revision ID: aae936cb27a1
Revises: 16a3ab210695
Create Date: 2026-03-12 23:49:11.385012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae936cb27a1'
down_revision: Union[str, Sequence[str], None] = '16a3ab210695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'jobs',
        sa.Column(
            'priority',
            sa.String(length=20),
            nullable=False,
            server_default='normal'
        )
    )
    op.alter_column('jobs', 'priority', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'priority')
    # ### end Alembic commands ###
