"""add refresh token rotation fields

Revision ID: c0e59fc6e7e5
Revises: abbd0fe2c1c5
Create Date: 2026-03-31 13:13:20.756720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e59fc6e7e5'
down_revision: Union[str, Sequence[str], None] = 'abbd0fe2c1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('replaced_by_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'replaced_by_token_hash')
    op.drop_column('refresh_tokens', 'rotated_at')
    # ### end Alembic commands ###
